In [185]:
import pandas as pd
import numpy as np

In [186]:
molecules = pd.read_csv("molecules.csv")
molecules.drop_duplicates(inplace=True)
stimuli = pd.read_csv("stimuli.csv")
tables1 = pd.read_csv("tableS1.csv")
tables2 = pd.read_csv("tableS2.csv")

# Expt 1

In [187]:
tables1 = pd.read_csv("tableS1.csv")
expt1_mixture_definitions = tables1[(tables1['Type'] == 'mixture') & (tables1['Experiment'] == 'Exp1')].copy()
expt1_mixture_definitions.dropna(axis=1, how='all', inplace=True)
for i in range(1,11):
    expt1_mixture_definitions = pd.merge(expt1_mixture_definitions, molecules[['CID', 'IsomericSMILES']], left_on=f'Mix Component {i}', right_on='CID', how='left')
    expt1_mixture_definitions[f'Mix Component {i}'] = expt1_mixture_definitions['IsomericSMILES']
    expt1_mixture_definitions.drop(columns=['CID', 'IsomericSMILES'], inplace=True)
desired_list = ['ID In Exp 1'] + [f'Mix Component {i}' for i in range(1,11)]
expt1_mixture_definitions = expt1_mixture_definitions[desired_list]
desired_column_names = ['Mixture Label'] + [f'smi_{i}' for i in range(10)]
expt1_mixture_definitions.columns = desired_column_names
for i in range(10, 43):
    expt1_mixture_definitions[f'smi_{i}'] = np.nan
expt1_mixture_definitions['Dataset'] = 'Ravia 1'
ordered_cols = ["Dataset"] + expt1_mixture_definitions.columns[:-1].to_list()
expt1_mixture_definitions = expt1_mixture_definitions[ordered_cols]

In [188]:
expt1_behavior = pd.read_csv("behavior_2.csv")
expt1_behavior = expt1_behavior[(expt1_behavior['Stimulus 1'] <= 270) & (expt1_behavior['Stimulus 2'] <= 270)]
expt1_behavior['Stimulus 1'] -= 256
expt1_behavior['Stimulus 2'] -= 256
expt1_behavior['Dataset'] = 'Ravia 1'
expt1_behavior.columns = ['Mixture 1', 'Mixture 2', 'Experimental Values', 'Dataset']
expt1_behavior['Experimental Values'] = (100-expt1_behavior['Experimental Values'])/100
ordered_cols = ["Dataset"] + expt1_behavior.columns[:-1].to_list()
expt1_behavior = expt1_behavior[ordered_cols]

In [189]:
expt1_mixture_definitions

,Dataset,Mixture Label,smi_0,smi_1,smi_2,smi_3,smi_4,smi_5,smi_6,smi_7,...,smi_33,smi_34,smi_35,smi_36,smi_37,smi_38,smi_39,smi_40,smi_41,smi_42
0,Ravia 1,1,CC(C)C1=CC=C(C=C1)C=O,CCC1=NC=CN=C1,CC1=CC=CC=C1,CCCCSCCCC,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Ravia 1,2,CC(=O)C1=CC=CC=C1,C1=CC=C(C=C1)C=O,CC(=O)O[C@@H]1C[C@@H]2CC[C@]1(C2(C)C)C,COC(=O)C1=CC=CC=C1N,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Ravia 1,3,CC1=CC(=O)CC(C1)(C)C,CCCCCOC(=O)CCCC,COC1=CC=CC=C1,CC1=CC=C(C=C1)OC(=O)C(C)C,COC1=C(C=CC(=C1)CC=C)O,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Ravia 1,4,CC(C)CCOC(=O)C,CCCCNCCCC,CCCC(=O)OCC,CCCCCC(C=C)O,CCCCCCCC1CCC(=O)O1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ravia 1,5,COC1=CC=CC=C1,CCCCNCCCC,CC1=CN=C(C=N1)C,CCCCCCO,CCCCCC1CCC(=O)O1,CCCCSCCCC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Ravia 1,6,CC(=O)C1=CC=CC=C1,CC(C)C1=CC=C(C=C1)C=O,CC1(C2CCC(O1)(CC2)C)C,CCCC(=O)SC,CCCC(=O)OCCC,CC1=CC=CC=C1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Ravia 1,7,C1=CC=C(C=C1)C=O,C1=CC=C(C=C1)/C=C/C=O,CC1=CC=C(C=C1)OC,CC1(C2CCC(O1)(CC2)C)C,CCCC(CC)O,CC(C1=CC=CC=C1)C(OC)OC,COC(=O)C1=CC=CC=C1N,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Ravia 1,8,CC(C)CCOC(=O)C,CCCCCOC(=O)CCCC,CCCCCCCO,CCCC(CC)O,COC1=CC=CC=C1,CCCCCC(C=C)O,CC1=CC=CC=C1C=O,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Ravia 1,9,CC1=CC(=O)CC(C1)(C)C,CC(=O)O[C@@H]1C[C@@H]2CC[C@]1(C2(C)C)C,CCCCCCC=O,CCCCCCO,CCCCCC1CCC(=O)O1,CC1=CC2=C(C=C1)N=CC=C2,CCCCCCCCCOC(=O)C,CCCCCCCC1CCC(=O)O1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Ravia 1,10,CC(=O)C1=CC=CC=C1,CCC/C=C/C=O,CC1=CC=C(C=C1)OC(=O)C,COC1=CC=CC=C1,CCCCCCCO,CCCCCC1CCC(=O)O1,CC1=CCC2CC1C2(C)C,C1=CSC=C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Ravia 1,11,CCCCCOC(=O)CCCC,CC1=CC=C(C=C1)OC(=O)C,CC1(C2CCC(O1)(CC2)C)C,COC1=C(C=CC(=C1)CC=C)O,COC(=O)C1=CC=CC=C1N,C=CCCC(=O)O,CCCCSCCCC,C1=CC=C(C=C1)CCO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Ravia 1,12,CCC/C=C/C=O,C1=CC=C(C=C1)/C=C/C=O,CC1=CC=C(C=C1)OC(=O)C(C)C,CCCC(CC)O,COC(=O)C1=CC=CC=C1O,CCCCC(=O)O,C1=CC=C(C=C1)CCO,CCCC(=O)OCCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Ravia 1,13,CC1=CC=C(C=C1)OC(=O)C,CC1=CC=C(C=C1)OC,C1CCC(CC1)O,COC1=C(C=CC(=C1)CC=C)O,CC(C1=CC=CC=C1)C(OC)OC,CC1=CC2=C(C=C1)N=CC=C2,CCCCC(=O)O,C=CCCC(=O)O,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Ravia 1,14,C1=CC=C(C=C1)C=O,CC1(C2CCC(O1)(CC2)C)C,CCCCCCC=O,CCCCCCCO,CCCCCC1CCC(=O)O1,CC1=CC2=C(C=C1)N=CC=C2,COC(=O)C1=CC=CC=C1O,CCCCCCCCCOC(=O)C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [190]:
expt1_behavior.head(20)

    Dataset  Mixture 1  Mixture 2  Experimental Values
0   Ravia 1          1          1             0.108636
1   Ravia 1          1          2             0.719545
2   Ravia 1          1          3             0.615227
3   Ravia 1          1          4             0.779091
4   Ravia 1          1          5             0.409545
5   Ravia 1          1          6             0.745455
6   Ravia 1          1          8             0.551591
7   Ravia 1          1          9             0.647727
8   Ravia 1          1         10             0.643409
9   Ravia 1          1         11             0.689773
10  Ravia 1          2          2             0.129773
11  Ravia 1          2          4             0.394091
12  Ravia 1          2          5             0.590000
13  Ravia 1          2          7             0.348182
14  Ravia 1          2          8             0.497955
15  Ravia 1          2         10             0.703409
16  Ravia 1          2         12             0.745909
17  Ravia 1          2         13             0.422273
18  Ravia 1          2         14             0.395000
19  Ravia 1          3          2             0.533409

# Expt 2

In [191]:
tables1 = pd.read_csv("tableS1.csv")
expt2_mixture_definitions = tables1[(tables1['Type'] == 'mixture') & (tables1['Experiment'] == 'Exp2')].copy()
expt2_mixture_definitions.dropna(axis=1, how='all', inplace=True)
for i in range(1,11):
    expt2_mixture_definitions = pd.merge(expt2_mixture_definitions, molecules[['CID', 'IsomericSMILES']], left_on=f'Mix Component {i}', right_on='CID', how='left')
    expt2_mixture_definitions[f'Mix Component {i}'] = expt2_mixture_definitions['IsomericSMILES']
    expt2_mixture_definitions.drop(columns=['CID', 'IsomericSMILES'], inplace=True)
desired_list = ['ID In Exp 1'] + [f'Mix Component {i}' for i in range(1,11)]
expt2_mixture_definitions = expt2_mixture_definitions[desired_list]
desired_column_names = ['Mixture Label'] + [f'smi_{i}' for i in range(10)]
expt2_mixture_definitions.columns = desired_column_names
for i in range(10, 43):
    expt2_mixture_definitions[f'smi_{i}'] = np.nan
expt2_mixture_definitions['Dataset'] = 'Ravia 2'
ordered_cols = ["Dataset"] + expt2_mixture_definitions.columns[:-1].to_list()
expt2_mixture_definitions = expt2_mixture_definitions[ordered_cols]

In [192]:
expt2_behavior = pd.read_csv("behavior_2.csv")
expt2_behavior = expt2_behavior[(expt2_behavior['Stimulus 1'] > 270) & (expt2_behavior['Stimulus 2'] > 270)]
expt2_behavior['Stimulus 1'] -= 270
expt2_behavior['Stimulus 2'] -= 270
expt2_behavior['Dataset'] = 'Ravia 2'
expt2_behavior.columns = ['Mixture 1', 'Mixture 2', 'Experimental Values', 'Dataset']
expt2_behavior['Experimental Values'] = (100-expt2_behavior['Experimental Values'])/100
ordered_cols = ["Dataset"] + expt2_behavior.columns[:-1].to_list()
expt2_behavior = expt2_behavior[ordered_cols]

# Merge in

In [193]:
mixture_definitions = pd.read_csv("../mixture_smi_definitions_clean.csv")

In [195]:
mixture_definitions = pd.concat([mixture_definitions, expt1_mixture_definitions, expt2_mixture_definitions])

In [197]:
mixture_definitions.to_csv("../mixture_smi_definitions_clean.csv", index=False)

In [201]:
mixtures_combined = pd.read_csv("../mixtures_combined.csv")

In [202]:
mixtures_combined = pd.concat([mixtures_combined, expt1_behavior, expt2_behavior])

In [205]:
mixtures_combined.to_csv("../mixtures_combined.csv", index=False)

# Expt 5

In [137]:
expt5_mixture_definitions = tables1[(tables1['Type'] == 'mixture') & (tables1['Experiment'] == 'Exp4,5')].copy()

In [138]:
expt5_mixture_definitions

,Type,Experiment,CID,ID,Compared To ID,ID In Exp 1,ID In Exp 2,Dilution1,Intensity1,Dilution2,...,Mix Component 26,Mix Component 27,Mix Component 28,Mix Component 29,Mix Component 30,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48
285,mixture,"Exp4,5",NaN,M1,M11,1,NaN,100.00%,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,24.0,1.0,NaN,24.0,24.0
286,mixture,"Exp4,5",NaN,M2,M12,2,NaN,100.00%,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,14.0,2.0,NaN,14.0,16.0
287,mixture,"Exp4,5",NaN,M3,M13,3,NaN,100.00%,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,13.0,3.0,NaN,13.0,19.0
288,mixture,"Exp4,5",NaN,M4,M14,4,NaN,100.00%,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,17.0,4.0,NaN,17.0,10.0
289,mixture,"Exp4,5",NaN,M5,M15,5,NaN,100.00%,NaN,NaN,...,24915.0,31266.0,10430.0,0.0,0.0,28.0,5.0,NaN,28.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,mixture,"Exp4,5",NaN,M116,M106,116,NaN,100.00%,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,18.0,116.0,NaN,NaN,NaN
401,mixture,"Exp4,5",NaN,M117,M107,117,NaN,100.00%,NaN,NaN,...,31266.0,8842.0,10430.0,0.0,0.0,28.0,117.0,NaN,NaN,NaN
402,mixture,"Exp4,5",NaN,M118,M108,118,NaN,100.00%,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,25.0,118.0,NaN,NaN,NaN
403,mixture,"Exp4,5",NaN,M119,M109,119,NaN,100.00%,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,14.0,119.0,NaN,NaN,NaN
404,mixture,"Exp4,5",NaN,M120,M110,120,NaN,100.00%,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,18.0,120.0,NaN,NaN,NaN

In [179]:
stimuli[(stimuli['Experiment'] == 'Exp4,5') & (stimuli['Type'] == 'mono-molecule')]

,Stimulus,Type,Experiment,CID,ID,Compared To ID,ID In Exp 1,ID In Exp 2,Dilution1,Dilution2,Dilution3
134,134,mono-molecule,"Exp4,5",7799,NaN,NaN,1,NaN,100.00%,NaN,NaN
135,135,mono-molecule,"Exp4,5",1068,NaN,NaN,2,NaN,10.00%,NaN,NaN
136,136,mono-molecule,"Exp4,5",6590,NaN,NaN,3,NaN,1.00%,NaN,NaN
137,137,mono-molecule,"Exp4,5",31244,NaN,NaN,4,NaN,100.00%,NaN,NaN
138,138,mono-molecule,"Exp4,5",1031,NaN,NaN,5,NaN,10.00%,NaN,NaN
139,139,mono-molecule,"Exp4,5",176,NaN,NaN,6,NaN,10.00%,NaN,NaN
140,140,mono-molecule,"Exp4,5",180,NaN,NaN,7,NaN,10.00%,NaN,NaN
141,141,mono-molecule,"Exp4,5",3776,NaN,NaN,8,NaN,100.00%,NaN,NaN
142,142,mono-molecule,"Exp4,5",7363,NaN,NaN,9,NaN,10.00%,NaN,NaN
143,143,mono-molecule,"Exp4,5",7150,NaN,NaN,10,NaN,100.00%,NaN,NaN
144,144,mono-molecule,"Exp4,5",14286,NaN,NaN,11,NaN,100.00%,NaN,NaN
145,145,mono-molecule,"Exp4,5",61138,NaN,NaN,12,NaN,100.00%,NaN,NaN
146,146,mono-molecule,"Exp4,5",8025,NaN,NaN,13,NaN,100.00%,NaN,NaN
147,147,mono-molecule,"Exp4,5",19310,NaN,NaN,14,NaN,100.00%,NaN,NaN
148,148,mono-molecule,"Exp4,5",6561,NaN,NaN,15,NaN,1.00%,NaN,NaN
149,149,mono-molecule,"Exp4,5",7793,NaN,NaN,16,NaN,100.00%,NaN,NaN
150,150,mono-molecule,"Exp4,5",443158,NaN,NaN,17,NaN,100.00%,NaN,NaN
151,151,mono-molecule,"Exp4,5",264,NaN,NaN,18,NaN,10.00%,NaN,NaN
152,152,mono-molecule,"Exp4,5",11552,NaN,NaN,19,NaN,10.00%,NaN,NaN
153,153,mono-molecule,"Exp4,5",12020,NaN,NaN,20,NaN,100.00%,NaN,NaN
154,154,mono-molecule,"Exp4,5",22386,NaN,NaN,21,NaN,100.00%,NaN,NaN
155,155,mono-molecule,"Exp4,5",62336,NaN,NaN,22,NaN,100.00%,NaN,NaN
156,156,mono-molecule,"Exp4,5",527,NaN,NaN,23,NaN,10.00%,NaN,NaN
157,157,mono-molecule,"Exp4,5",263,NaN,NaN,24,NaN,100.00%,NaN,NaN
158,158,mono-molecule,"Exp4,5",9609,NaN,NaN,25,NaN,10.00%,NaN,NaN
159,159,mono-molecule,"Exp4,5",6584,NaN,NaN,26,NaN,100.00%,NaN,NaN
160,160,mono-molecule,"Exp4,5",1032,NaN,NaN,27,NaN,10.00%,NaN,NaN
161,161,mono-molecule,"Exp4,5",6569,NaN,NaN,28,NaN,100.00%,NaN,NaN
162,162,mono-molecule,"Exp4,5",84682,NaN,NaN,29,NaN,100.00%,NaN,NaN
163,163,mono-molecule,"Exp4,5",8063,NaN,NaN,30,NaN,100.00%,NaN,NaN
164,164,mono-molecule,"Exp4,5",6276,NaN,NaN,31,NaN,100.00%,NaN,NaN
165,165,mono-molecule,"Exp4,5",10448,NaN,NaN,32,NaN,1.00%,NaN,NaN
166,166,mono-molecule,"Exp4,5",8857,NaN,NaN,33,NaN,100.00%,NaN,NaN
167,167,mono-molecule,"Exp4,5",7895,NaN,NaN,34,NaN,100.00%,NaN,NaN
168,168,mono-molecule,"Exp4,5",7284,NaN,NaN,35,NaN,100.00%,NaN,NaN
169,169,mono-molecule,"Exp4,5",11173,NaN,NaN,36,NaN,100.00%,NaN,NaN
170,170,mono-molecule,"Exp4,5",261,NaN,NaN,37,NaN,10.00%,NaN,NaN
171,171,mono-molecule,"Exp4,5",5284503,NaN,NaN,38,NaN,100.00%,NaN,NaN
172,172,mono-molecule,"Exp4,5",5318042,NaN,NaN,39,NaN,100.00%,NaN,NaN
173,173,mono-molecule,"Exp4,5",8103,NaN,NaN,40,NaN,100.00%,NaN,NaN
174,174,mono-molecule,"Exp4,5",637566,NaN,NaN,41,NaN,100.00%,NaN,NaN
175,175,mono-molecule,"Exp4,5",638011,NaN,NaN,42,NaN,100.00%,NaN,NaN
176,176,mono-molecule,"Exp4,5",637776,NaN,NaN,43,NaN,10.00%,NaN,NaN
177,177,mono-molecule,"Exp4,5",10890,NaN,NaN,44,NaN,100.00%,NaN,NaN
178,178,mono-molecule,"Exp4,5",24915,NaN,NaN,45,NaN,100.00%,NaN,NaN
179,179,mono-molecule,"Exp4,5",31266,NaN,NaN,46,NaN,100.00%,NaN,NaN
180,180,mono-molecule,"Exp4,5",6184,NaN,NaN,47,NaN,100.00%,NaN,NaN
181,181,mono-molecule,"Exp4,5",3314,NaN,NaN,48,NaN,100.00%,NaN,NaN
182,182,mono-molecule,"Exp4,5",8842,NaN,NaN,49,NaN,100.00%,NaN,NaN
183,183,mono-molecule,"Exp4,5",10430,NaN,NaN,50,NaN,10.00%,NaN,NaN
184,184,mono-molecule,"Exp4,5",Blank,NaN,NaN,51,NaN,100.00%,NaN,NaN

In [168]:
expt5_raw_behavior = pd.read_csv("tableS3.csv")
expt5_raw_behavior = expt5_raw_behavior[expt5_raw_behavior['Experiment'] == 'Exp4']

pairs = set(list(zip(expt5_raw_behavior['Mixture1'], expt5_raw_behavior['Mixture2'])))

# Create an empty list to store results
results_list = []

# Iterate through all pairs
for stim1, stim2 in pairs:
    # Subset the dataframe for this pair
    subset = expt5_raw_behavior[(expt5_raw_behavior['Mixture1'] == stim1) & (expt5_raw_behavior['Mixture2'] == stim2)]

    print(f"{stim1, stim2}: {len(subset)}")
    
    # Calculate the ratio if the subset is not empty
    if len(subset) > 0:
        ratio = subset['IsCorrect'].sum() / len(subset)
        
        # Add the result to the results list
        results_list.append({
            'Mixture 1': stim1,
            'Mixture 2': stim2,
            'Experimental Values': ratio
        })

# Create the results dataframe from the list
expt5_behavior = pd.DataFrame(results_list)

(7, 17): 56
(25, 35): 56
(62, 72): 48
(81, 91): 64
(67, 77): 48
(26, 36): 56
(44, 54): 48
(90, 100): 64
(3, 13): 56
(21, 31): 56
(22, 32): 56
(86, 96): 64
(8, 18): 56
(49, 59): 48
(27, 37): 56
(68, 78): 48
(45, 55): 48
(63, 73): 48
(41, 51): 48
(64, 74): 48
(82, 92): 64
(85, 95): 64
(4, 14): 56
(50, 60): 48
(69, 79): 48
(46, 56): 48
(5, 15): 56
(23, 33): 56
(87, 97): 64
(9, 19): 56
(1, 11): 56
(65, 75): 48
(10, 20): 56
(28, 38): 56
(83, 93): 64
(6, 16): 56
(88, 98): 64
(47, 57): 48
(24, 34): 56
(42, 52): 48
(43, 53): 48
(84, 94): 64
(61, 71): 48
(70, 80): 48
(29, 39): 56
(48, 58): 48
(89, 99): 64
(2, 12): 56
(66, 76): 48
(30, 40): 56

In [169]:
expt5_behavior[expt5_behavior['Mixture 1'] != expt5_behavior['Mixture 2']].sort_values(by='Mixture 1')

    Mixture 1  Mixture 2  Experimental Values
30          1         11             0.750000
47          2         12             0.589286
8           3         13             0.500000
22          4         14             0.500000
26          5         15             0.660714
35          6         16             0.517857
0           7         17             0.428571
12          8         18             0.482143
29          9         19             0.375000
32         10         20             0.750000
9          21         31             0.589286
10         22         32             0.910714
27         23         33             0.482143
38         24         34             0.732143
1          25         35             0.464286
5          26         36             0.714286
14         27         37             0.500000
33         28         38             0.607143
44         29         39             0.589286
49         30         40             0.910714
18         41         51             0.354167
39         42         52             0.500000
40         43         53             0.395833
6          44         54             0.395833
16         45         55             0.354167
25         46         56             0.520833
37         47         57             0.500000
45         48         58             0.354167
13         49         59             0.312500
23         50         60             0.395833
42         61         71             0.666667
2          62         72             0.541667
17         63         73             0.604167
19         64         74             0.458333
31         65         75             0.645833
48         66         76             0.729167
4          67         77             0.645833
15         68         78             0.666667
24         69         79             0.604167
43         70         80             0.770833
3          81         91             0.437500
20         82         92             0.359375
34         83         93             0.468750
41         84         94             0.468750
21         85         95             0.671875
11         86         96             0.406250
28         87         97             0.390625
36         88         98             0.421875
46         89         99             0.421875
7          90        100             0.468750

In [172]:
expt5_behavior

    Mixture 1  Mixture 2  Experimental Values
0           7         17             0.428571
1          25         35             0.464286
2          62         72             0.541667
3          81         91             0.437500
4          67         77             0.645833
5          26         36             0.714286
6          44         54             0.395833
7          90        100             0.468750
8           3         13             0.500000
9          21         31             0.589286
10         22         32             0.910714
11         86         96             0.406250
12          8         18             0.482143
13         49         59             0.312500
14         27         37             0.500000
15         68         78             0.666667
16         45         55             0.354167
17         63         73             0.604167
18         41         51             0.354167
19         64         74             0.458333
20         82         92             0.359375
21         85         95             0.671875
22          4         14             0.500000
23         50         60             0.395833
24         69         79             0.604167
25         46         56             0.520833
26          5         15             0.660714
27         23         33             0.482143
28         87         97             0.390625
29          9         19             0.375000
30          1         11             0.750000
31         65         75             0.645833
32         10         20             0.750000
33         28         38             0.607143
34         83         93             0.468750
35          6         16             0.517857
36         88         98             0.421875
37         47         57             0.500000
38         24         34             0.732143
39         42         52             0.500000
40         43         53             0.395833
41         84         94             0.468750
42         61         71             0.666667
43         70         80             0.770833
44         29         39             0.589286
45         48         58             0.354167
46         89         99             0.421875
47          2         12             0.589286
48         66         76             0.729167
49         30         40             0.910714