In [6]:
import pandas as pd
import numpy as np
import os
import sys
from pathlib import Path

script_dir = Path(os.path.abspath(""))
base_dir = Path(*script_dir.parts[:-2])
sys.path.append( str(base_dir / 'src/') )
DATASET_DIR = base_dir / 'datasets'

In [27]:
mean_df = pd.read_csv(DATASET_DIR / "mixtures/mixture_rdkit_mean_definitions_clean.csv")
pna_df = pd.read_csv(DATASET_DIR / "mixtures/mixture_rdkit_definitions_clean.csv")
mix_df = pd.read_csv(DATASET_DIR / "mixtures/mixtures_combined.csv")
smi_df = pd.read_csv(DATASET_DIR / "mixtures/mixture_smi_definitions_clean.csv")

smi_df['length'] = smi_df.apply(lambda row: len(row[smi_df.filter(like='smi_').columns].dropna()), axis=1)

In [29]:
pna_df

,Dataset,Mixture Label,0,1,2,3,4,5,6,7,...,790,791,792,793,794,795,796,797,798,799
0,Snitz 1,1,0.957874,0.014039,0.011828,0.017821,0.012443,0.010455,0.018601,0.011978,...,0.904243,0.979139,0.99582,0.988329,0.9991,0.99972,0.950837,0.984909,0.934865,0.289400
1,Snitz 1,2,0.955011,0.018586,0.008236,0.014254,0.009872,0.007548,0.017269,0.011723,...,0.904243,0.979139,0.99582,0.988329,0.9991,0.99972,0.950837,0.984909,0.934865,0.214125
2,Snitz 1,3,0.779125,0.005600,0.008611,0.019901,0.013371,0.010411,0.041993,0.026742,...,0.904243,0.979139,0.99582,0.988329,0.9991,0.99972,0.950837,0.991969,0.934865,0.304671
3,Snitz 1,4,0.944446,0.013755,0.007820,0.015712,0.011182,0.006509,0.018425,0.016404,...,0.904243,0.979139,0.99582,0.988329,0.9991,0.99972,0.950837,0.984909,0.934865,0.340924
4,Snitz 1,5,0.941628,0.017256,0.012197,0.024124,0.018669,0.010249,0.026607,0.021831,...,0.904243,0.979139,0.99582,0.988329,0.9991,0.99972,0.950837,0.984909,0.934865,0.212185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,Ravia 2,10,0.914559,0.017564,0.017186,0.022707,0.017080,0.016664,0.025681,0.018480,...,0.904243,0.979139,0.99582,0.988329,0.9991,0.99972,0.950837,0.984909,0.934865,0.161181
776,Ravia 2,11,0.838744,0.052298,0.048263,0.076932,0.066255,0.046214,0.079506,0.081519,...,0.904243,0.979139,0.99582,0.988329,0.9991,0.99972,0.950837,0.984909,0.934865,0.211165
777,Ravia 2,12,0.964181,0.014004,0.012541,0.020707,0.014772,0.010779,0.021370,0.014602,...,0.904243,0.979139,0.99582,0.988329,0.9991,0.99972,0.950837,0.984909,0.934865,0.161181
778,Ravia 2,13,0.898442,0.028221,0.028216,0.039556,0.028555,0.031180,0.044347,0.030410,...,0.904243,0.979139,0.99582,0.988329,0.9991,0.99972,0.950837,0.984909,0.934865,0.211165
779,Ravia 2,14,0.952699,0.007544,0.017621,0.032483,0.025185,0.012886,0.040505,0.032216,...,0.904243,0.979139,0.99582,0.988329,0.9991,0.99972,0.950837,0.984909,0.934865,0.169652

In [30]:
# In smi_df, check if each row is unique compared to other rows based on values from columns 2 onwards  
set_list = {}
for i, row in smi_df.iterrows():
    curr_set = frozenset(row[2:].dropna())
    if curr_set in set_list.keys():
        print(f"Duplicate row found between {set_list[curr_set]} and [{row['Dataset']}, {row['Mixture Label']}]")
    else:
        set_list[curr_set] = [row['Dataset'], row['Mixture Label']]

Duplicate row found between ['Ravia 4', 11] and [Ravia 4, 35]
Duplicate row found between ['Ravia 4', 13] and [Ravia 4, 40]
Duplicate row found between ['Ravia 4', 46] and [Ravia 4, 52]
Duplicate row found between ['Ravia 4', 42] and [Ravia 4, 56]
Duplicate row found between ['Ravia 4', 89] and [Ravia 4, 92]
Duplicate row found between ['Ravia 4', 82] and [Ravia 4, 99]
Duplicate row found between ['Bushdid', 159] and [Bushdid, 317]
Duplicate row found between ['Snitz 1', 3] and [Snitz 3, 2]
Duplicate row found between ['Snitz 1', 32] and [Snitz 3, 3]
Duplicate row found between ['Snitz 1', 45] and [Snitz 3, 8]
Duplicate row found between ['Snitz 1', 20] and [Snitz 3, 20]
Duplicate row found between ['Snitz 1', 15] and [Snitz 3, 21]
Duplicate row found between ['Snitz 1', 27] and [Snitz 3, 48]
Duplicate row found between ['Snitz 2', 5] and [Ravia 1, 2]
Duplicate row found between ['Snitz 2', 8] and [Ravia 1, 4]
Duplicate row found between ['Snitz 2', 12] and [Ravia 1, 6]
Duplicate row found between ['Snitz 2', 3] and [Ravia 1, 8]

In [35]:
# In smi_df, make the first instance of each unique row the canonical representation. 
# Make this column duplicate as False for the first instance of the row, and define all other instances of the row by the specific Dataset and Mixture Label of the first instance.
canonical_smi_df = smi_df.copy()
canonical_smi_df['Duplicate'] = False
canonical_smi_df['Duplicate Of'] = np.nan

canonical_pna_df = pna_df.copy()
canonical_pna_df['Duplicate'] = False
canonical_pna_df['Duplicate Of'] = np.nan

canonical_mean_df = mean_df.copy()
canonical_mean_df['Duplicate'] = False
canonical_mean_df['Duplicate Of'] = np.nan
for i, row in smi_df.iterrows():
    curr_set = frozenset(row[2:].dropna())
    if curr_set in set_list.keys():
        if set_list[curr_set] != [row['Dataset'], row['Mixture Label']]:
            for dataframe in [canonical_smi_df, canonical_pna_df, canonical_mean_df]:
                dataframe.loc[i, 'Duplicate'] = True
                dataframe.loc[i, 'Duplicate Of'] = str(set_list[curr_set])
            

# Rearrange columns to bring the Duplicate Columns to the front
canonical_smi_df = canonical_smi_df[['Dataset', 'Mixture Label', 'length', 'Duplicate', 'Duplicate Of'] + list(canonical_smi_df.columns[2:-2])]
canonical_pna_df = canonical_pna_df[['Dataset', 'Mixture Label', 'Duplicate', 'Duplicate Of'] + list(canonical_pna_df.columns[2:-2])]
canonical_mean_df = canonical_mean_df[['Dataset', 'Mixture Label', 'Duplicate', 'Duplicate Of'] + list(canonical_mean_df.columns[2:-2])]

/tmp/ipykernel_1200531/1399265203.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['Ravia 4', 11]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  dataframe.loc[i, 'Duplicate Of'] = str(set_list[curr_set])

In [39]:
canonical_smi_df.to_csv("mixture_smi_definitions_clean_found_duplicates.csv", index=False)
canonical_pna_df.to_csv("mixture_rdkit_definitions_clean_found_duplicates.csv", index=False)
canonical_mean_df.to_csv("mixture_rdkit_mean_definitions_clean_found_duplicates.csv", index=False)